[flutter_local_notifications] Add custom repeat interval - periodicallyShowWithDuration method
MaikuB/flutter_local_notifications pull request #2197
Opened 2024-01-01 19:27 UTC by mateuszluczak1996

Add an option to set custom time for periodically showed notifications.

The problem that I have encountered on iOS devices is that repeating interval must be set to 60 seconds minimum, but I don't think that is the problem for real use case scenarios.

**Sample usage:**
```
    await flutterLocalNotificationsPlugin.periodicallyShowWithDuration(
      1,
      'repeating period title',
      'repeating period body',
      const Duration(minutes: 5),
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
    );
```

2024-01-17 10:20 UTC, MaikuB commented
Thanks for the PR. Will need time to give this one a good review compared to some other ones

2024-03-04 08:46 UTC, MaikuB requested changes
Thanks. Got to test it out and works well. Besides the comment on the PR, do you think you'd be able to look at the following

- addressing the linter issues picked up by Dart analyzer
- I ran into the limitation you mentioned with Apple's APIs when the duration needs to be a minute. Rather than letting it run into a native exception that may not bubble up to be caught on the Dart side, could validation be added to ensure the duration is at least a minute on all the platform-specific implementations and throw an [ArgumentError](https://api.dart.dev/stable/3.3.0/dart-core/ArgumentError-class.html)? This would allow checking the argument up-front. If you're not sure how to do it, it'd be similar to how the ID is validated to ensure it's within range where there's a `validateId()` call in the plugin

2024-06-28 02:02 UTC, MaikuB commented
In the interest of merging the PR, I've made the changes and will have this merged in soon :)

2024-06-28 02:03 UTC, merged

2024-06-28 06:44 UTC, yfujiki commented
Great addition!! 

Only thing I want further is to specify initial time (currently it defaults to current time). But i guess it is limited by iOS side capability.

2024-07-03 12:04 UTC, shrigashlesh commented
Looks great!! About what @yfujiki said, can the offset datetime (say something like the zonedSchedule) be used in tandem with the periodic duration? It might be able to solve multiple scheduling scenarios.

2024-07-03 12:05 UTC, pandey407 commented
Looks great!! About what @yfujiki said, can the offset datetime (say something like the zonedSchedule) be used in tandem with the periodic duration? It might be able to solve multiple scheduling scenarios.